In [8]:
import numpy as np
from random import random
import itertools

In [9]:
# Setup up testing robot and objective coordinates
robot_coords = np.array([random()*20 - 10, random()*20 - 10]);
obj_coords = np.empty((5,2), dtype=float);
for i in range(0, obj_coords.shape[0]):
    for j in range(0, obj_coords.shape[1]):
        obj_coords[i][j] = random()*20 - 10;
print('Robot Coordinates:')
print(robot_coords)
print('Objective Coordinates:')
print(obj_coords)

Robot Coordinates:
[ 4.86649128 -7.26277876]
Objective Coordinates:
[[ 1.92210082  5.71374822]
 [-2.91605701 -1.36331488]
 [-8.1272246   5.78720811]
 [ 0.69637305 -8.31135624]
 [-6.15268404 -8.72847916]]


In [10]:
#
N_obj = obj_coords.shape[0]
print('Number of Objective Coordinates:', N_obj)

Number of Objective Coordinates: 5


In [12]:
# Agregate robot and objective coordinates
obj_positions = np.empty((N_obj + 1, 2), dtype=float)
for i in range(0, N_obj):
    if i == 0:
        obj_positions[i][0] = robot_coords[0]
        obj_positions[i][1] = robot_coords[1]
    else:
        obj_positions[i][0] = obj_coords[i-1][0]
        obj_positions[i][1] = obj_coords[i-1][1]
print(obj_positions)

[[ 4.86649128 -7.26277876]
 [ 1.92210082  5.71374822]
 [-2.91605701 -1.36331488]
 [-8.1272246   5.78720811]
 [ 0.69637305 -8.31135624]
 [ 0.          0.        ]]


In [13]:
# Compute square distances array
obj_distances = np.empty((N_obj + 1, N_obj + 1), dtype=float)
for i in range(0, N_obj + 1):
    for j in range(0, N_obj + 1):
        x_diff = obj_positions[i][0] - obj_positions[j][0]
        y_diff = obj_positions[i][1] - obj_positions[j][1]
        obj_distances[i][j] = (x_diff**2 + y_diff**2)**(1/2)
print(obj_distances)


[[ 0.         13.30637771  9.76584518 18.41572181  4.29993032  8.74246492]
 [13.30637771  0.          8.57278211 10.04959391 14.07856398  6.02838206]
 [ 9.76584518  8.57278211  0.          8.84795155  7.83102355  3.21900853]
 [18.41572181 10.04959391  8.84795155  0.         16.63205917  9.97715176]
 [ 4.29993032 14.07856398  7.83102355 16.63205917  0.          8.34047829]
 [ 8.74246492  6.02838206  3.21900853  9.97715176  8.34047829  0.        ]]


In [15]:
# Compute the permutations
N_perm = np.math.factorial(N_obj)

obj_list = []
for i in range(0, N_obj):
    obj_list.append(i+1)
perm = itertools.permutations(obj_list)

obj_permutations = np.zeros((N_perm, N_obj), dtype=int)
ctr = 0
for i in perm:
    obj_permutations[ctr] = np.array(i)
    ctr = ctr + 1

obj_totaldistances = np.zeros((N_perm, 1), dtype=float)
for i in range(0, N_perm):
    total_dist = obj_distances[0][obj_permutations[i][0]]
    for j in range(0, N_obj - 1):
        total_dist += obj_distances[obj_permutations[i][j]][obj_permutations[i][j+1]]
    total_dist += obj_distances[obj_permutations[i][N_obj - 1]][0]
    obj_totaldistances[i] = total_dist
print(obj_totaldistances)

[[64.44211374]
 [53.34467174]
 [65.06185921]
 [66.44353522]
 [56.00730961]
 [68.48642761]
 [57.11788991]
 [48.0633403 ]
 [59.78052777]
 [61.31336278]
 [48.68308578]
 [59.27047039]
 [62.78353345]
 [66.82784733]
 [64.82642584]
 [66.97900633]
 [66.20810185]
 [64.31636846]
 [52.33370933]
 [65.43257282]
 [50.29081694]
 [63.54083942]
 [62.76993495]
 [62.92109395]
 [62.10322357]
 [51.00578157]
 [67.76886712]
 [69.15054313]
 [55.27615061]
 [67.75526861]
 [59.82489781]
 [47.3321813 ]
 [64.09526685]
 [62.92109395]
 [52.99782485]
 [64.31636846]
 [60.44464329]
 [66.09668833]
 [59.04936877]
 [63.54083942]
 [60.43104478]
 [59.27047039]
 [49.99481917]
 [68.13958072]
 [51.39009368]
 [66.97900633]
 [63.86921169]
 [61.31336278]
 [61.95206458]
 [52.89751497]
 [62.33637668]
 [63.86921169]
 [49.84366017]
 [60.43104478]
 [66.99796265]
 [54.50524614]
 [63.94410785]
 [62.76993495]
 [54.88955824]
 [66.20810185]
 [69.66060051]
 [68.13958072]
 [66.22243361]
 [65.43257282]
 [67.75526861]
 [68.48642761]
 [55.12499

In [16]:
obj_minimum_dist = obj_totaldistances[0]
obj_minimum_perm_index = 0
for i in range(0, N_perm):
    if obj_totaldistances[i] < obj_minimum_dist:
        obj_minimum_dist = obj_totaldistances[i]
        obj_minimum_perm_index = i

print('Optimal Objective Priority:')
print(obj_permutations[obj_minimum_perm_index])
print('Minimum Travel Distance:', obj_minimum_dist)
    

Optimal Objective Priority:
[4 2 3 1 5]
Minimum Travel Distance: [45.7993463]
