In [84]:
import numpy as np
from random import random
import itertools

In [141]:
# Setup up testing robot and objective coordinates
robot_coords = np.array([random()*20 - 10, random()*20 - 10]);
obj_coords = np.empty((5,2), dtype=float);
for i in range(0, obj_coords.shape[0]):
    for j in range(0, obj_coords.shape[1]):
        obj_coords[i][j] = random()*20 - 10;
print('Robot Coordinates:')
print(robot_coords)
print('Objective Coordinates:')
print(obj_coords)

Robot Coordinates:
[-9.42875964  1.74856255]
Objective Coordinates:
[[-7.39770136  0.68294264]
 [-2.96724392 -5.39100913]
 [ 3.02002037  1.46290097]
 [ 7.74345057 -9.24144303]
 [ 6.92627959 -5.52780433]]


In [142]:
#
N_obj = obj_coords.shape[0]
print('Number of Objective Coordinates:', N_obj)

Number of Objective Coordinates: 5


In [143]:
# Agregate robot and objective coordinates
obj_positions = np.empty((N_obj + 1, 2), dtype=float)
for i in range(0, N_obj):
    if i == 0:
        obj_positions[i][0] = robot_coords[0]
        obj_positions[i][1] = robot_coords[1]
    else:
        obj_positions[i][0] = obj_coords[i-1][0]
        obj_positions[i][1] = obj_coords[i-1][1]
print(obj_positions)

[[-9.42875964  1.74856255]
 [-7.39770136  0.68294264]
 [-2.96724392 -5.39100913]
 [ 3.02002037  1.46290097]
 [ 7.74345057 -9.24144303]
 [ 7.8479481   1.49579302]]


In [144]:
# Compute square distances array
obj_distances = np.empty((N_obj + 1, N_obj + 1), dtype=float)
for i in range(0, N_obj + 1):
    for j in range(0, N_obj + 1):
        x_diff = obj_positions[i][0] - obj_positions[j][0]
        y_diff = obj_positions[i][1] - obj_positions[j][1]
        obj_distances[i][j] = (x_diff**2 + y_diff**2)**(1/2)
print(obj_distances)


[[ 0.          2.29363107  9.62936494 12.4520571  20.38786468 17.27855673]
 [ 2.29363107  0.          7.51810104 10.44687805 18.10380935 15.26730341]
 [ 9.62936494  7.51810104  0.          9.10073718 11.38177568 12.82171682]
 [12.4520571  10.44687805  9.10073718  0.         11.70016126  4.82803978]
 [20.38786468 18.10380935 11.38177568 11.70016126  0.         10.73774454]
 [17.27855673 15.26730341 12.82171682  4.82803978 10.73774454  0.        ]]


In [145]:
# Compute the permutations
N_perm = np.math.factorial(N_obj)

obj_list = []
for i in range(0, N_obj):
    obj_list.append(i+1)
perm = itertools.permutations(obj_list)

obj_permutations = np.zeros((N_perm, N_obj), dtype=int)
ctr = 0
for i in perm:
    obj_permutations[ctr] = np.array(i)
    ctr = ctr + 1

obj_totaldistances = np.zeros((N_perm, 1), dtype=float)
for i in range(0, N_perm):
    total_dist = obj_distances[0][obj_permutations[i][0]]
    for j in range(0, N_obj - 1):
        total_dist += obj_distances[obj_permutations[i][j]][obj_permutations[i][j+1]]
    total_dist += obj_distances[obj_permutations[i][N_obj - 1]][0]
    obj_totaldistances[i] = total_dist
print(obj_totaldistances)

[[58.62893182]
 [54.86611829]
 [55.00026556]
 [49.21134922]
 [59.54951464]
 [57.52341184]
 [61.23932326]
 [65.78857234]
 [65.92271961]
 [57.62949668]
 [62.15990608]
 [49.31743406]
 [62.98654979]
 [61.88102981]
 [71.29861241]
 [59.37672321]
 [65.50969607]
 [54.69332686]
 [71.57141441]
 [65.91664534]
 [63.25935179]
 [55.10027613]
 [61.23324899]
 [58.72894239]
 [67.31080656]
 [63.54799303]
 [69.05803309]
 [63.26911675]
 [69.3308351 ]
 [67.30473229]
 [75.29709079]
 [75.56989279]
 [81.07993286]
 [58.72894239]
 [77.31711933]
 [54.69332686]
 [71.66842453]
 [71.66235026]
 [75.70404006]
 [55.10027613]
 [69.91512372]
 [49.31743406]
 [80.25328915]
 [79.97441287]
 [76.21767361]
 [59.37672321]
 [74.1915708 ]
 [57.62949668]
 [69.81511315]
 [74.36436224]
 [82.48479374]
 [74.1915708 ]
 [82.75759574]
 [69.91512372]
 [75.19100595]
 [75.46380795]
 [83.58423945]
 [61.23324899]
 [88.13348854]
 [65.50969607]
 [79.8744023 ]
 [79.97441287]
 [75.59795522]
 [65.91664534]
 [67.30473229]
 [57.52341184]
 [71.83514

In [147]:
obj_minimum_dist = obj_totaldistances[0]
obj_minimum_perm_index = 0
for i in range(0, N_perm):
    if obj_totaldistances[i] < obj_minimum_dist:
        obj_minimum_dist = obj_totaldistances[i]
        obj_minimum_perm_index = i

print('Optimal Objective Priority:')
print(obj_permutations[obj_minimum_perm_index])
print('Minimum Travel Distance:', obj_minimum_dist)
    

Optimal Objective Priority:
[3 5 4 2 1]
Minimum Travel Distance: [49.21134922]
